(function () {
    this.hatemile_configuration_symbols = [{
        'symbol': '!',
        'description': 'symbol-exclamation-mark'
    }, {
        'symbol': '"',
        'description': 'symbol-double-quotes'
    }, {
        'symbol': '#',
        'description': 'symbol-number'
    }, {
        'symbol': '$',
        'description': 'symbol-dollar'
    }, {
        'symbol': '%',
        'description': 'symbol-percent'
    }, {
        'symbol': '&',
        'description': 'symbol-ampersand'
    }, {
        'symbol': '\'',
        'description': 'symbol-single-quote'
    }, {
        'symbol': '(',
        'description': 'symbol-open-parenthesis'
    }, {
        'symbol': ')',
        'description': 'symbol-close-parenthesis'
    }, {
        'symbol': '*',
        'description': 'symbol-asterisk'
    }, {
        'symbol': '+',
        'description': 'symbol-plus'
    }, {
        'symbol': ',',
        'description': 'symbol-comma'
    }, {
        'symbol': '-',
        'description': 'symbol-hyphen'
    }, {
        'symbol': '.',
        'description': 'symbol-dot'
    }, {
        'symbol': '/',
        'description': 'symbol-slash'
    }, {
        'symbol': ':',
        'description': 'symbol-colon'
    }, {
        'symbol': ';',
        'description': 'symbol-semicolon'
    }, {
        'symbol': '<',
        'description': 'symbol-less-than'
    }, {
        'symbol': '=',
        'description': 'symbol-equals'
    }, {
        'symbol': '>',
        'description': 'symbol-greater-than'
    }, {
        'symbol': '?',
        'description': 'symbol-question-mark'
    }, {
        'symbol': '@',
        'description': 'symbol-at'
    }, {
        'symbol': '[',
        'description': 'symbol-open-bracket'
    }, {
        'symbol': '\\',
        'description': 'symbol-backslash'
    }, {
        'symbol': ']',
        'description': 'symbol-close-bracket'
    }, {
        'symbol': '^',
        'description': 'symbol-caret'
    }, {
        'symbol': '_',
        'description': 'symbol-underscore'
    }, {
        'symbol': '`',
        'description': 'symbol-grave-accent'
    }, {
        'symbol': '{',
        'description': 'symbol-open-brace'
    }, {
        'symbol': '|',
        'description': 'symbol-vertical-bar'
    }, {
        'symbol': '}',
        'description': 'symbol-close-brace'
    }, {
        'symbol': '~',
        'description': 'symbol-tilde'
    }];

}).call(this);
